global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#andrey_svezhincev'
