version: '3'
services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - back_net
      - front_net

  fluentd:
    container_name: fluentd
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.1.1
    environment:
      - discovery.type=single-node
      #- cluster.initial_master_nodes=elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: kibana:7.1.1
    ports:
      - "5601:5601"

networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
