version: '3.3'
services:
  mongo_db:
    container_name: mongo_db
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
         - post_db
         - comment_db

  ui:
    container_name: ui
#    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    env_file: .env
    ports:
      - 9292:9292/tcp
    networks:
      - front_net

  post:
    container_name: post
#    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    env_file: .env
    networks:
      - back_net
      - front_net
    ports:
      - "5000:5000"

  comment:
    container_name: comment
#    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    env_file: .env
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
