version: '3.3'
services:
  mongo_db:
    container_name: mongo_db
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
         - post_db
         - comment_db

  ui:
#    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    env_file: .env
    ports:
      - 9292:9292/tcp
    networks:
      - front_net

  post:
    container_name: post
#    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    env_file: .env
    networks:
      - back_net
      - front_net

  comment:
    container_name: comment
#    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    env_file: .env
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
      - front_net

  mongodb-exporter:
    image: xendera/mongodb-exporter
    container_name: mongodb-exporter
    ports:
      - 9216:9216
#    command: -mongodb.tls -mongodb.tls-ca /etc/certs/mycert.crt -mongodb.tls-private-key /etc/certs/mycert.pem
#    volumes:
#      - /etc/certs:/etc/certs
    environment:
      - MONGODB_URL=mongodb://mongo_db
    networks:
      - back_net

volumes:
  prometheus_data:
  post_db:

networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
